### PR TITLE
Handle HTTP client errors 

### PR DESCRIPTION
**Pull request by hannesgassert**
Test: turn off your network connection and try to send any GCM notification.

### CODE REVIEW

**Comment by hannesgassert** [comment]
@h2soft @iasandcb please merge & publish, thanks!

**Comment by iasandcb** [comment]
Thanks for your nice work, @hannesgassert !

**Comment by hannesgassert** [comment]
You're welcome. Please let me know when this is published on npm.

**Comment by iasandcb** [comment]
node-gcm 1.0.1 is just published. Enjoy the new edition !

**Comment by hannesgassert** [comment]
Lovely, thanks.

**Pull request merged**
